name: CI
on: [push, pull_request]

jobs:
  e2e:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: licitagil_test
        ports:
          - "5432:5432"
        options: >-
          --health-cmd "pg_isready -U postgres" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: |
          cd api
          npm ci
          cp .env.ci .env
          npx prisma migrate deploy
          node ./dist/index.js &
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/licitagil_test
      - run: |
          cd web
          npm ci
          npm run build
          npx http-server dist -p 5173 &
      - run: npx wait-on http://localhost:3000/healthz http://localhost:5173
      - run: |
          cd web
          npx cypress run --config baseUrl=http://localhost:5173
